apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demo
  labels:
    app: demo
spec:
  containers:
  - name: app
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
