apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  labels:
    app: demo
spec:
  containers:
  - name: demo-app-container
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    emptyDir: {}
  - name: app-volume
    hostPath:
      path: /var/lib/app
