apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
  namespace: demo
  labels:
    app: demo
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k3s/demo:v2.0.0
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /readyz
        port: 8080
