apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
  labels:
    app: mycontainer
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecrets
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecrets
          key: password
